Revert "drivers: qcom: rpmh-rsc: modularize RSC controller driver"
This reverts commit 13eec9363471db4aa3944295c681980ee601af30.
It breaks allmodconfig:

  drivers/soc/qcom/rpmhpd.o: In function `rpmhpd_aggregate_corner':
  rpmhpd.c:(.text+0x8f8): undefined reference to `rpmh_write'
  rpmhpd.c:(.text+0x900): undefined reference to `rpmh_write_async'
  rpmhpd.c:(.text+0x9c4): undefined reference to `rpmh_write_async'
  rpmhpd.c:(.text+0xa3c): undefined reference to `rpmh_write_async'

It is not obvious that QCOM_RPMH should be tristate in the first place
when QCOM_RPMHPD needs it compiled in.

Bug: 140224784
Signed-off-by: Quentin Perret <qperret@google.com>
Change-Id: I154b2d2b369c3654c41595bad91abd5a47d15206