Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit a95ca7d93e304031858af11c6501bd7a00c06b54.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>